### PR TITLE
RabbitMQ config additions

### PR DESCRIPTION
**Pull request by andyshinn**
This is just some ideas for tuning the cluster. I've found it not very stable in my production Rancher environment so I'm thinking of parameters to tune. Any additions to this?

### CODE REVIEW

**Comment by ddmng** [comment]
I can't do any test at the moment but I'm going to merge it and build the image on docker hub

**Comment by ddmng** [comment]
@andyshinn I've just created `0.2.0-testing` image on docker hub to test the new version and started a new RabbitMQ stack on Rancher changing only the `-conf` version from `0.1.0` to `0.2.0-testing` but something is not working.
The first node goes up but the `-conf` container reports:
`29/07/2016 15:06:352016-07-29T14:06:35Z rabbit-test_rabbitmq_2 /confd[1]: ERROR Unable to process template /etc/confd/templates/rabbitmq.tmpl, template: rabbitmq.tmpl:3: unexpected {{end}}`

Scaling causes the new containers going up but the new rabbit node is not joining the cluster and `-conf` reports same error as before.

Note: I'm working on a separate branch: https://github.com/ddmng/catalog-dockerfiles/tree/andyshinn-rabbitmq_config

As soon as it will work I think I will have to create the `0.2.0` version:
- on `catalog-dockerfiles`
- in the corresponding `-conf` built image on docker hub 
- on `community-catalog`
  Than I will have to make a new PR to Rancher guys to merge on main catalog.
  What do you think?

**Comment by andyshinn** [comment]
Oops, there is extra `{{end}}` in the conditionals a the end of line. I will try it out more soon.

**Comment by ddmng** [comment]
Extra `{{end}}` later in line 11 too; I tried to fix that config but still doesn't work. I added you as collaborator on the docker hub `rabbitmq-conf` repo (https://hub.docker.com/r/rdaneel/rabbitmq-conf/) so that you can push there and test quickly.

**Comment by inabhi9** [comment]
I've _forked_ this repo and produce my own version with additional configs. However I completely removed conf image and extend original rabbitmq image with confd. It also has rancher template
You can have a look here https://github.com/inabhi9/rancher-rabbitmq

Let me know what do you guys think. I can make a pull request if it makes sense.

**Comment by ddmng** [comment]
Hi @inabhi9 !
Other stacks in Rancher have their own confd service and it seems reasonable to stick on the official images in services where possible: with this in mind I separated the `confd` from Rabbit and pointed to the offical `3.6.1-management` RabbitMQ DockerHub tag. I assume you are using something like `supervisord` to start both `rabbitmq-server` and `confd` and IMHO it's against the logic of microservices, where each container represents a service/process.
I think the best way to bring in this stack the new options that you have added is to manage them in the separate `confd` service, like all the other Rancher stacks.

**Comment by ddmng** [comment]
@andyshinn I can't see what's wrong in this PR these days, but if you have time to fix it I'll give it a quick run in my local cluster.

**Comment by andyshinn** [comment]
I think these are fine. I'm testing this in my own forked image in production and the config seems fine.

Unfortunately, these options haven't fixed the stability issues I've been having with RabbitMQ over the Rancher network. It is really unstable and I experience weekly cluster splits that never self heal. I'm still trying to figure out the "magic" config to get it working better.

**Comment by andyshinn** [comment]
Also, please double check this PR before building. I don't have my fork public (I was just testing with a locally built image and config). I think I may have mis-placed a comma in this. I'll try and check in the next week when I have some time to play with RabbitMQ again.

**Comment by inabhi9** [comment]
Hi @ddmng,

Your points are valid and I agree with you. In this case I would suggest @andyshinn If he wants to look at the config file in my repo. I'm using that image for a week without any issue.

**Comment by andyshinn** [comment]
What are you using for `RABBITMQ_CLUSTER_PARTITION_HANDLING` and `RABBITMQ_NET_TICKTIME`? As far as I can tell, the config is identical other than formatting. Is there a feature of your config that we should add to this one?

**Comment by inabhi9** [comment]
I'm using 'autoheal' and default 60 for net tick time with two node cluster.
I tried config of this PR but somehow server couldn't came up. So I thought there might be config file issue.
Also you may consider the env variable for overriding the template entirely.

**Comment by ddmng** [comment]
Hi @andyshinn @inabhi9 
I've just merged your contribs here in `andyshinn-rabbitmq_config` branch and started a 2 nodes cluster on my servers to see if I can reproduce that @andyshinn is reporting. The corresponding catalog is at https://github.com/ddmng/community-catalog and points to the image at https://hub.docker.com/r/rdaneel/rabbitmq-conf/  pushed with `0.2.0-testing` tag.

If you can, please run a test on your sides. When we are ready I'll merge the PR under `0.2.0`, fix the READMEs and other small stuff and send a PR to rancher.

**Comment by inabhi9** [comment]
Hi @ddmng 

I also have a suggestion on scaling mode. I saw that you've to do of avoiding multiple rabbitmq server on same host. As rancher doesn't have feature to handle that much complex rule, I recommend to use global scheduler with host tag like other template does. Anyway most of the users, don't want to host multiple instance on same host.

Let me know what do you think.

**Comment by andyshinn** [comment]
I will test the new image soon (I am creating new env next week or two).

I would not want default global container since I have mix of data and service nodes in same env. I just create an anti-affinity rule like so:

```
io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
```

**Comment by inabhi9** [comment]
I also tried soft anti affinity rule but thing is if your node goes down
for more a few second rancher may create another instance on same node and
resync will start (if your using HA) when your old host comes back online,
it won't rebalance and user will have to manually rebalance it.

Global scheduler can be used along with labels. I also use multiple
services on same host like role=rabbit, role=api on same host

**Comment by andyshinn** [comment]
You can't have two of same `role` tag on same host. Though, you can do something like `api=true` and `role=true`. But "global" to me means "all" in this environment, which I am not too keen on (maybe that makes sense once it works really well and stable, but it hasn't proven that to me yet).

**Comment by inabhi9** [comment]
Sorry that I just wrote it that way. And yes you're right global means on `all` in this environment but you can control that using labels and rules that on which x/y/z node should run the service. Does it make sense?

**Comment by inabhi9** [comment]
@ddmng I tested new image and config now being generated fine and loaded correctly by the rabbitmq so It should be good to go.

Are you considering the env variable for replacing the template entirely for more advance use case and config?

**Comment by ddmng** [comment]
@inabhi9 I'd like to test the cluster failure scenario you raised. What I've understood from your description is:
1. I deploy a 3 nodes RabbitMQ on hosts `A`, `B`, `C` in a cluster of _4 nodes_ (there is also node `D` then)
2. node `B` goes down (I would simulate with a shutdown command)
3. Rancher pulls a new RabbitMQ instance on node `D` trying to respect the `Scale=3` setting on the stack
4. node `B` comes back and starts all the stopped services, including RabbitMQ

Then what have you experienced at this point?

About labels: labels are causing me a bit headache; I'd like to use them only when needed, e.g. when I have Fiber Channel links connecting to a set of servers to a storage or some other physical constrains that services need for working. 
If needed, I think we could include a label in RabbitMQ stack BUT it would at least be _configurable_ . I don't know how to specify a label as a `rancher-compose` user-specified parameter and passing that to the `docker-compose` configuration. I also asked that in Rancher Forum but no replies: https://forums.rancher.com/t/use-of-rancher-compose-variable-in-label-name/3102 . Any idea on how it would be done?
About custom template: I've just seen the piece of code in your entrypoint and it look useful for testing. I will include it ASAP. As far as I can see in Rancher's UI you could only pass this custom config when upgrading the service, right?

**Comment by inabhi9** [comment]
On Failure scenario:

In your strategy, you have 3 nodes A/B/C and one extra node D with scale number of 3 (so assume no rabbit server on D initially). Now,

1) If B goes down, rancher will start new instance on D (with soft negative affinity rule but no guarantee if not rule is not specify though we assume here it'll)
2) Now after few minutes, B comes back. In this case rancher won't kill instance on D and resume service on B as scale constrain already satisfied (somewhat related to https://github.com/rancher/rancher/issues/2558). In this case, If user manually kill the service on D, rancher may reschedule on B.
3) Let's assume that we have rebalancing in place and rancher kills on D and start on B. But then it can be questioned that Do we really want to spin off new instance as soon as desired scale goes down or we want to wait for few minutes? Because if new instance starts up and if rabbit server configured in auto HA mode, it'll start syncing with new node and it's little costly as per rabbitmq doc.
4) When we want to scale down, then how and who will tell rancher that which instance would be removed? It may possible that in multiple failure some X node became master and rancher may remove it.

Scaling down rabbitmq is little tricky and I feel that it should be kept manual task.

So what do you think?

About labels: I've seem few catalog which uses labale in rancher-compose. I'll try to find it.

On Custom template: Yes it'll be only possible either on upgrade or on initial setup

**Comment by ddmng** [comment]
OK Clear. So this means that Rancher's rebalance algorithm can, in some cases, cause a perfomance issue on RabbitMQ's cluster. 
Even in this case I still think that the limitations of adding a fixed label to the `community-catalog`'s Rabbit stack are too many for the advantages they introduce. If there was a way to specify a label in stack's options so that it can be passed to `docker-compose` then maybe that would be the optimal solution.

> About labels: I've seem few catalog which uses labale in rancher-compose. I'll try to find it.

If you can find it, I think many stacks in the catalog would really benefit from it.

**Comment by inabhi9** [comment]
@ddmng Here are a few catalog where you can see the host label config used in docker-compose

https://rancher.abhi9.in/env/1a12/catalog/community:janitor?catalogId=library
https://rancher.abhi9.in/env/1a12/catalog/community:sysdig?catalogId=library

**Comment by ddmng** [comment]
It seems your private rancher... I would need a login to see and... this is not the right place to share it 😀

Just to be clear: the issue is not using a label in a compose... I'm full of labels in my private catalog to stick services to type of servers. The point is to make the label configurable in rancher compose. If we include a label in rabbit catalog entry, we force everyone out there to use it in their infrastructure in order to ship a rabbitmq server. I think that the presence of a label should be a choice and even the label name should be configurable each time. A configurable, optional label is something I could not accomplish in my past attempts. 
If you have something please post rancher and docker composes here or in a gist.

**Comment by ddmng** [comment]
@andyshinn @inabhi9 
Polishing work done:
- updated READMEs on dockerfile and catalog
- added confd configuration override via env variable
- moved new stuff to `0.2.0` directory and restored `0.1.0` to original content
- pushed image `rdaneel/rabbitmq-conf` with tag `0.2.0` and aligned catalog

Just started on my cluster; deploy and scale seems to work for now.
I keep it running for a while and waiting for some feedback before issuing a PR to the community catalog.

**Comment by inabhi9** [comment]
@ddmng That makes sense to make labels optional. I don't know what rancher does in case of scheduling rule with blank labels that needs to tested other than that there is no conditional based definition in docker compose. So for now, keep it as it is.

Looking forward to your feedback. I'll ditch forked image and try to implement this catalog. And great work. Thanks!

**Pull request merged**
